[package]
name = "img_stegano"
version = "0.1.0"
edition = "2021"

[lib]
path = "./src/lib.rs"

[workspace]
members = [
	"stegano-core",
	"stegano-cli",
	"stegano-wasm",
]

[dependencies]
img_stegano_core = {path = "./stegano-core"}