[package]
name = "img_stegano_cli"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
structopt = "0.3.26"
img_stegano = {path = ".."}
anyhow = "1.0.75"
thiserror = "1.0.50"
